### ISSUE TITLE
not work in Blender 2.77

### ISSUE THREAD

**Issue by Leroy-X** [waylow/Add_Camera_Rigs#1]
Report error when I add the camera rig.

![qq 20160402153323](https://cloud.githubusercontent.com/assets/13515498/14225089/9ef834ac-f8e8-11e5-822f-6322f2c8e805.png)

**Comment by waylow** [comment]
thanks Leroy, try it now.

**Comment by Leroy-X** [comment]
thanks for you fix that, it's work now, just have one suggestion, in the pose mode , the add armature should be in disable status, like the "single bone", and you know , if add armature in pose mode, it will be report error : )

Thanks!

![04](https://cloud.githubusercontent.com/assets/13515498/14226108/ef2142e4-f90a-11e5-829d-b5dcf7c81ac9.png)

**Comment by waylow** [comment]
Thanks again Leyroy-X,
Updating now so it can only operate in Object mode.

**Comment by Leroy-X** [comment]
Thanks waylow too:+1:
