### ISSUE TITLE
The 2d camera rig has dependency cycles.

### ISSUE THREAD

**Issue by freen75** [waylow/Add_Camera_Rigs#10]
Blender 3.6.4, Windows

When adding a  2d camera rig Blender instantly starts complaining about dependency cycles.

> Dependency cycle detected:
>   CA2d_Camera/PARAMETERS_EVAL() depends on
>   CA2d_Camera/DRIVER(shift_x) via 'Driver -> Driven Property'
>   CA2d_Camera/PARAMETERS_EVAL() via 'RNA Target -> Driver'
> Dependency cycle detected:
>   CA2d_Camera/PARAMETERS_EVAL() depends on
>   CA2d_Camera/DRIVER(shift_x) via 'Driver -> Driven Property'
>   CA2d_Camera/PARAMETERS_EVAL() via 'RNA Target -> Driver'
> Dependency cycle detected:
>   CA2d_Camera/PARAMETERS_EVAL() depends on
>   CA2d_Camera/DRIVER(shift_y) via 'Driver -> Driven Property'
>   CA2d_Camera/PARAMETERS_EVAL() via 'RNA Target -> Driver'
> Dependency cycle detected:
>   CA2d_Camera/PARAMETERS_EVAL() depends on
>   CA2d_Camera/DRIVER(shift_y) via 'Driver -> Driven Property'
>   CA2d_Camera/PARAMETERS_EVAL() via 'RNA Target -> Driver'
> Detected 4 dependency cycles
>

**Comment by freen75** [comment]
I managed to get around this on my local copy of the rig by:
- copying the driver from the lens attribute of the camera,
- adding a property to the armature called "lens"
- pasting the driver there
- using the new property in the "lens" variable for the drivers of shift_x and shift_y on the camera.

It seems to work, even if it isn't the most elegant solution. Would be nice to have this or some other solution in the addon.

**Comment by waylow** [comment]
Hi Beorn.
Thanks for the report - and your work around.

Damien is the maintainer of the 2d camera rig, however, with your info I can make an adjustment and poke him about getting it included in the next release.

cheers man

**Comment by freen75** [comment]
Great, thanks mate!
