### ISSUE TITLE
Crane Camera missing Crane Arm setting

### ISSUE THREAD

**Issue by yak007** [waylow/Add_Camera_Rigs#11]
Blender 4.1.1, Windows, steam build and blender installer build, addon version 1.6.0

When added Crane Camera to the scene, console will report error

> Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\4.1\scripts\addons\add_camera_rigs\ui_panels.py", line 96, in draw
    col.prop(pose_bones["Crane_height"],
             ~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "Crane_height" not found'

And missing the Arm Length and Height setting in toolbar
![20240619012403](https://github.com/waylow/add_camera_rigs/assets/8154804/f91e7a4f-84f1-4d87-9652-c8599dc4a600)

**Comment by waylow** [comment]
Thanks for the report yak :)

It seems we made some changes to the naming convention in the 4.1 release but forgot to update the UI.
This is already working correctly in the upcoming 4.2 release.

I'm not sure if there are any more updates to the 4.1 release.  So if you really need the crane rig to work before then....

You can change that "Crane_height" to "Crane_Height"
And "Crane_arm" to "Crane_Arm" in the ui_panels.py file.

Sorry for the inconvenience but thanks again for pointing out the issue.
