### ISSUE TITLE
not showing rigging

### ISSUE THREAD

**Issue by MODOS11** [waylow/Add_Camera_Rigs#12]
Auto phyton on,  but no luck in getting this to work on 4.1

**Comment by waylow** [comment]
Hi Modos,

Could you provide more information?

I'm assuming you have activated it from the add-ons that ship with Blender 4.1  (and not the outdated code here on Github)

What exactly isn't working?
Does it show in the menu, does it throw an error, does the ui not show in the n-panel?

I'll need more information to be able to assist.

**Comment by MODOS11** [comment]
I needed to turn bone visibility on and allow auto python: Problem solved.
Thank you for helping.
Domenico
