### ISSUE TITLE
Error activating addon in 2.78c

### ISSUE THREAD

**Issue by thelapisfox** [waylow/Add_Camera_Rigs#4]
When I try to activate the addon, I get this error message;

`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\addon_utils.py", line 349, in enable
    mod.register()
  File "C:\Users\diago\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\camera_dolly_crane_rigs.py", line 915, in register
    bpy.types.INFO_MT_camera_add.append(add_dolly_button)
AttributeError: 'RNA_Types' object has no attribute 'INFO_MT_camera_add'`

**Comment by thelapisfox** [comment]
Nevermind, it seems I was not installing it right. I did not know I had to put the entire folder into the scripts folder. Thought I had to use the 'install from file' option. Once placed in the right place, it worked fine.

**Comment by thelapisfox** [comment]
Nevermind, it seems I was not installing it right. I did not know I had to put the entire folder into the scripts folder. Thought I had to use the 'install from file' option. Once placed in the right place, it worked fine.

**Comment by camic** [comment]
sorry
![capture d ecran de 2017-06-13 20-21-26](https://user-images.githubusercontent.com/11509346/27110258-fc99dc56-5075-11e7-8cfe-2b9a649f1d99.png)
 no.  I tried to add the .zip and/or the extracted files, folder, files, what ever.  it would be fine to know what it mean to  "placed in the right place".  also activated auto run scripts.

**Comment by camic** [comment]
![capture d ecran de 2017-06-13 20-16-18](https://user-images.githubusercontent.com/11509346/27110387-e5dfa0b2-5076-11e7-87ac-6bb17eda40f2.png)
