### ISSUE TITLE
Camera Rig and Viewport control

### ISSUE THREAD

**Issue by rbergeron3d** [waylow/Add_Camera_Rigs#6]
Hello!

First, sorry if this isn't the place to bring this up! Let me know and I'll write somewhere else about this. Just thought to go directly to the source as you might know much more about what is doable and not camera-wise in Blender :)

I have been trying to come up with a camera rig in Blender for a while before finding that it was actually already all done as a built-in Add-on! This is great!

The only thing that I find is not working really well is the fact that the camera is controlling the entire setup when moving it through the Viewport (It seems to do that as soon as I put a camera under a parent)

I am working with cameras everyday at work (In Maya though) and would like to have some of the flexibility of the simple rig I am normally using but in Blender as I am trying to make the move from Maya to Blender at home. (So far I love it : D)

Some of it is:
- Camera is free from the rig by being the child of all. It seems to be the case here except if I try to move it in the camera viewport using let's say the walk or fly tool or normal 3d navigation keys, it will move the entire hierarchy.
- Camera is affected by the aim, but still can tweak the rotation of it as an extra offset (Tracking an object without being perfect)
- Having an extra Root offset so you can keep the main root where the focus of the camera is to create an easy rotation around an element (Like these 360 cameras in every Michael Bay movies:P)

All of this while still being able to control the camera from the camera viewport... So far my tests brought me to some poor results where the camera seems fine when tweaking it in the viewport, but if I animate the root for example, it becomes pretty unpredictable.

Thanks a lot and let me know if you need any more info or would like scene examples!

Ray

**Comment by waylow** [comment]
Hi Ray,
I've just pushed the latest code to github here so it is now in sync with the master version of Blender (currently 2.81 alpha).  There have been a few updates but it is mainly a refactor of the code an not to the actual functionality of the rig.

I'm not sure if you have seen the old demo - not a lot has changed in the design but some improvements in other areas have occurred.  
 https://vimeo.com/85884210
That might answer some of the issues you have.  The main confusing thing for native Maya users is Pose mode for armatures. 

I will make a new demo soon.  Hopefully before the next official release of Blender.

The camera is not meant to be animated in this rig (But I have left it unlocked so people can do little hacks if needed).  Everything should be done with the armature.  In the most recent updates I added properties to the rig for lens etc, so you only need to animate the one object.  ie - the rig.  So if you animate the camera in walk mode, you're animating the child and moving it away from the parent (the Camera control inside the rig)

If you want to animate the Camera control freely, there is a slider that will disable the auto aim and let you freely animate it (although it will still be part of the hierarchy - parented to the Root control)

If you were to constraint the aim bone to a target and then animate the offset to make it 'not perfect', isn't it possible just to animate the aim w/o an added offset?  This is how I do it. (I'm an animator).

Also don't forget that there is already an in-built extra root being the actual armature object itself.  You can also animate the object in object mode as well as the Root (and other controls) in Pose mode.  That way you can achieve many types of 360 shots, but if you are going for Michael Bay....I will need to develop some type of "Add Explosion" button haha.

As for animating the camera from the viewport, I'm not sure if it's possible in the way that you want with this rig, however you can select multiple bones and move and animate them from the camera perspective.  You can change the pivot if applicable and animate accordingly.
For example, if you wanted to rotate the camera around the aim point w/o using the root, you can select the camera control then the aim, make sure the pivot is set to 'active element' and then rotate on the world Z.  This will rotate you camera around the aim while looking through the camera.

Hopefully, that helps you out.  If there is anything that you still can't quite achieve feel free to send me an example vide (in Maya if need be). 
Cheers
Wayne

**Comment by rbergeron3d** [comment]
Hi Wayne!

Sorry for the lack of reply on my end! As you took the time to reply with
tons of great information, I wanted my reply to be more than just a "ok!!"
and then kept pushing it to later :P

Anyway I've been juggling between Blender and Unreal for a while and
haven't done much camera work in Blender since, but taking a deeper look
into Animating in Blender I can now understand a bit more some of my own
questions I had a few months ago.

Then in the past week I restarted using your rig inside Blender as I had
more complex animation that needed to be done and found it super useful.

Until, I discovered yesterday that the main point of my struggles (Being
that I couldn't control the camera from within the Viewport without moving
the entire rig) can be fixed by simply unchecking the checkbox in Blender
Preferences > Navigation > Fly & Walk > Camera Parent Lock. I'm not sure if
it's checked or unchecked by default as when I started playing in Blenders
6 months ago I pressed too many buttons :P But it totally fixes the main
issue I had with any camera rig!

So all of that for: now I can really say that I love your rig : D

Thanks a lot!

Ray

**Comment by rbergeron3d** [comment]
Hi Again!

I just did a quick update on your rig from what I was talking about now
that I understand a bit more what's happening under the hood :P

If you are interested anyway;

World CTRL controls the whole setup and isn't influenced by the Aim
World CTRL_A and B controls the camera but not the Aim (So they have to
point in the Aim direction when Activated)

This just helps for that type of movement where you want to follow a point
with multiple offsets. (So controls are Animated in the simplest way
possible as others are doing the offsets) Joining a quick example just to
show what I mean. In this example, if I wanted to animate an offset on the
Root of the camera, it was automatically moving the aim as well, resulting
in a weird movement. Having offsets help a lot in this case.

Anyway, Thanks for the base rig : D

Ray
