### ISSUE TITLE
Add control to orbit with rule of thirds

### ISSUE THREAD

**Issue by PFBourassa** [waylow/Add_Camera_Rigs#7]
Hi Wayne,

I'm not sure if this is best way to propose a feature, but I have a simple addition that would make this rig much more useful for my workflow.

In short, add a bone between the camera bone, and the camera object, which the user can rotate.

Currently, the camera can orbit around an object only if that object is dead center. But I frequently want the focal point to be framed according to the rule of thirds. 

Here's a quick video to show what I mean: https://youtu.be/F9mRygycBW4

Thanks!

**Comment by waylow** [comment]
Hi Parker.
Can you test the latest code.  I've added an offset controller.

**Comment by PFBourassa** [comment]
Sorry, I totally missed this earlier!

I tested 1.4.4 and it throws an error:
https://imgur.com/a/UDjt9dj

1.4.3 still work though.
Let me know if I can provide more info to help.

**Comment by waylow** [comment]
Oh I think that is because of GitHub.
Try removing it and then when you DL from github, delete the "-master" from the name of the zip.

I don't know how to stop GitHub from doing that.

**Comment by PFBourassa** [comment]
That didn't fix it. I updated to Blender 2.83.2 and got the same error.
Same deal on my laptop (Both windows 10)

**Comment by waylow** [comment]
Oh my bad - GitHub also does this to the folder inside the zip.
So that is the one that needs to have the "-master" removed.  (I think the name of the zip does not matter at all - but I could be wrong on that)

Sorry for the messing about.

**Comment by PFBourassa** [comment]
I tried changing both the names, and zipping it back up, but then it doesn't appear in the addon list.

**Comment by waylow** [comment]
Just download a daily build, this code is bundled with the development release.
It will be included in the next official release.

I have no idea why it isn't working for you.

**Comment by PFBourassa** [comment]
Oh, that worked!
Thanks for your help.

Yeah, this does exactly what I wanted. Thanks for adding it!

**Comment by ckat609** [comment]
Sorry for coming a few years late to the party, but... After reading this post and seeing the slider it got me wondering... wouldn't a separate bone for orbiting have worked better?  I mean, removing the influence of the rig on the camera is nice, but you lose some of the rig's functionality.  Also, adding a separate bone or empty for focusing would be nice.  So, basically, the current aim bone for composition, a bone/empty for focusing and the orbit bone/empty would be so nice.

**Comment by waylow** [comment]
Hi @ckat609 ,
Could you make a mock up of what you propose and I'll take a look?  (but not with empties - using bones will keep the animation data all connected to the same armature)

My overall feeling is that the rig shouldn't be too complicated to use though.  Adding some rarely needed features that make it more difficult to use in 99% of cases isn't ideal.
