### ISSUE TITLE
Was able to add camera and rig - now unable to

### ISSUE THREAD

**Issue by Stubeywoobey** [waylow/Add_Camera_Rigs#8]
### So I'm a bit of a newbie to Blender.

Have used the add on before to create camera and rig - the additional option are available under Add>Camera...

But then I deleted the cameras and folder etc to do some new stuff and the option is no longer available under under Add>Camera...I only see Add camera option.

I have saved my preferences and if I start a new Blender project the option of Camera and Rig is available - So I'm guessing I deleted something in this project that broke it.

Hope you can help.

Thanks

[TBC SPARK 3.blend.zip](https://github.com/waylow/add_camera_rigs/files/4913330/TBC.SPARK.3.blend.zip)

**Comment by waylow** [comment]
You need to enable the add-on in your user preferences.

This add-on ships with Blender so it is there by default (just not enabled unless you want it to be enabled)
