### ISSUE TITLE
Add Camera Rig doesn't work properly Blender 4.0.0 Alpha 

### ISSUE THREAD

**Issue by 3dbenart** [waylow/Add_Camera_Rigs#9]
![Screenshot (585)](https://github.com/waylow/add_camera_rigs/assets/145128067/04977de3-3019-455d-ac29-f5a1d7ad1c1d)
![Screenshot (584)](https://github.com/waylow/add_camera_rigs/assets/145128067/7e7ed3d8-36a3-418a-a2f7-499c50b66187)
You can see what Happens when I add it to the scene

**Comment by waylow** [comment]
Hi 3dbenart,
Bone collections are now replacing bone layers in 4.0

We will have to wait until the changes are finalised.
I will ask around to see if those changes are locked yet.

Thank you for bringing this up.

**Comment by waylow** [comment]
Hi 3dbenart,
Can you download the master branch and test.  I have amended the code to remove layers and use bone collections.

If all the camera rigs are working as expected I will get someone with access to push this into the official version for the 4.0 release.

**Comment by 3dbenart** [comment]
Thank you so much. I will test it out and let you know if it worked as expected .

**Comment by 3dbenart** [comment]
Can you please provide a download link ?

**Comment by waylow** [comment]
I'm not sure if this link will work for you.

https://github.com/waylow/add_camera_rigs/archive/refs/heads/master.zip


If it doesn't, just go to the main page here on github, then click the green button that says "CODE" and choose 'download zip' at the bottom

**Comment by 3dbenart** [comment]
I tried it and the same thing happened again .

**Comment by waylow** [comment]
The updates are in the queue to be merged with the official branch.
If you download a daily build in a day or 2, it should work in 4.0

Thanks again for reporting.

**Comment by 3dbenart** [comment]
Alright , many thanks .
